In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2,3],[4,5,6]])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])

In [5]:
#Transpuestas
vector_t = vector.T
print(vector_t)

[1 2 3]


In [6]:
matriz_t = matriz.T
print(matriz_t)

[[1 4]
 [2 5]
 [3 6]]


In [7]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]]


In [8]:
A = matriz
B = matriz 
C = A + B
print(A)
print(B)
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [9]:
D = matriz + escalar
print(D)

[[ 6.679  7.679  8.679]
 [ 9.679 10.679 11.679]]
